config/routes.rb
post '/issues/:id/iine', to: 'user_iines#create', as: 'iine_issue'
delete '/issues/:id/iine', to: 'user_iines#destroy'

app/models/iine_counter.rb
# frozen_string_literal: true

class IineCounter < ActiveRecord::Base
  belongs_to :issue, required: true
  has_many :user_iines, dependent: :destroy
end

app/models/iine_query_column.rb
# frozen_string_literal: true

class IineQueryColumn < QueryAssociationColumn
  def value_object(object)
    super || 0
  end
end

app/models/user_iine.rb
# frozen_string_literal: true

class UserIine < ActiveRecord::Base
  belongs_to :iine_counter, counter_cache: :count, required: true
  belongs_to :user, required: true

  validates :user, uniqueness: { scope: :iine_counter }
end

app/controllers/user_iines_controller.rb
# frozen_string_literal: true

class UserIinesController < ApplicationController
  before_action :set_issue
  before_action :set_user_iine

  def create
    @issue.create_iine_counter unless @issue.iine_counter
    UserIine.find_or_create_by!(iine_counter: @issue.iine_counter, user: User.current)
    @issue.iine_counter.reload
    render partial: 'redmine_iine/iine', locals: { issue: @issue }
  end

  def destroy
    @user_iine.try!(:destroy)
    @issue.iine_counter.reload
    render partial: 'redmine_iine/iine', locals: { issue: @issue }
  end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def set_user_iine
    @user_iine = UserIine.find_by(iine_counter: @issue.iine_counter, user: User.current)
  end
end

app/views/redmine_iine/_iine.html.erb
<% if User.current.iine?(issue) %>
  <%= link_to 'イイネヤメル', '#', class: 'redmine-iine', data: { custom_method: 'DELETE' } %>
<% else %>
  <%= link_to 'イイネ', '#', class: 'redmine-iine', data: { custom_method: 'POST' } %>
<% end %>
<span><%= issue.iine_count %>件</span>

app/views/redmine_iine/hooks/_view_issues_show_description_bottom.html.erb
<div id="redmine-iine" style="display: none;">
  <span class="redmine-iine-partial">
    <%== render partial: 'redmine_iine/iine', locals: { issue: issue } %>
  </span>
</div>

<script>
  $(document).on('click', '.redmine-iine', function(e) {
    e.preventDefault();
    $.ajax({
      method: $(this).data('custom-method'),
      url: '<%= iine_issue_path(issue) %>',
    }).done(function(html) {
      $('.redmine-iine-partial').html(html);
    });
  });

  $(function() {
    $('#redmine-iine').children().prependTo('#content > .contextual');
  });
</script>

app/views/redmine_iine/hooks/_view_layouts_base_content.html.erb
<%= link_to 'イイネ', '#', class: 'redmine-iine', style: 'display: none;' %>

<script>
  $('.redmine-iine').on('click', function(e) {
    e.preventDefault();
    alert('イイネ！');
  });

  $(function() {
    $('.redmine-iine').prependTo('#content .contextual').show();
  });
</script>